/* 
CREATION DE TABLE POUR AUTO-JOINTURE
*/
SELECT JOB FROM EMP WHERE ENAME='JONES';
SELECT ENAME FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME='JONES');


SELECT ENAME FROM EMP WHERE HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME='FORD');
